# Generated by Django 5.1.1 on 2025-01-22 12:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 13, 50, 41, 958661))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 13, 50, 41, 958661))),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 13, 50, 41, 958661))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 22, 13, 50, 41, 958661))),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_two', models.ImageField(default='files/images/banner-01.jpg', upload_to='uploads/')),
                ('image_three', models.ImageField(default='files/images/banner-01.jpg', upload_to='uploads/')),
                ('is_featured', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('size', models.CharField(blank=True, choices=[('SIZE_S', 'Size S'), ('SIZE_M', 'Size M'), ('SIZE_L', 'Size L'), ('SIZE_XL', 'Size XL')], max_length=50)),
                ('color', models.CharField(blank=True, choices=[('RED', 'Red'), ('GREEN', 'Green'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('WHITE', 'White'), ('GREY', 'Grey')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.category')),
            ],
        ),
    ]
