# Generated by Django 5.1.1 on 2025-02-08 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_coupon_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='ecommerce_app.coupon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 3, 59, 34, 62452)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 3, 59, 34, 62452)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 3, 59, 34, 63450)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 3, 59, 34, 63450)),
        ),
    ]
