# Generated by Django 5.1.1 on 2025-02-28 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_alter_cartorder_order_date_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 1, 18, 42, 381436)),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('process', 'processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 1, 18, 42, 380440)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 1, 18, 42, 380440)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 1, 18, 42, 380440)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 1, 18, 42, 380440)),
        ),
    ]
