# Generated by Django 5.1.1 on 2025-02-28 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_alter_cartorder_order_date_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 2, 17, 53, 290467)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 2, 17, 53, 289471)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 2, 17, 53, 289471)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 2, 17, 53, 290467)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 2, 17, 53, 290467)),
        ),
    ]
