# Generated by Django 5.1.1 on 2025-03-21 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0021_alter_cartorder_oid_alter_cartorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderproduct',
            options={'verbose_name_plural': 'Cart Order Item'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 1, 19, 42, 744709)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 1, 19, 42, 744709)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 1, 19, 42, 744709)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 1, 19, 42, 744709)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 1, 19, 42, 744709)),
        ),
        migrations.DeleteModel(
            name='CartorderItem',
        ),
    ]
