# Generated by Django 5.1.1 on 2025-01-28 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_contact_created_at_alter_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderproduct',
            name='item',
            field=models.CharField(default='Cart Item', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 41, 33, 511456)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 41, 33, 511456)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 41, 33, 511456)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 22, 41, 33, 511456)),
        ),
    ]
