# Generated by Django 5.1.1 on 2025-02-08 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_cartorder_coupons_alter_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 5, 25, 13, 125105)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 5, 25, 13, 126100)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 5, 25, 13, 127100)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 5, 25, 13, 127100)),
        ),
    ]
