# Generated by Django 5.1.1 on 2025-03-17 17:32

import datetime
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0020_alter_cartorder_order_date_alter_cartorder_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=5, max_length=50, null=True, prefix=''),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 18, 32, 26, 191943)),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', blank=True, length=5, max_length=50, null=True, prefix='SKU'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 18, 32, 26, 185548)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 18, 32, 26, 186548)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(default='files/images/banner-01.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(default='files/images/banner-01.jpg', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 18, 32, 26, 187945)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 18, 32, 26, 187945)),
        ),
    ]
